p <- read.csv("household_power_consumption.txt", sep=";", na.strings="?")
p <- subset(p, Date == "1/2/2007" | Date == "2/2/2007")
p[, "Date"] <- as.Date(strptime(p[, "Date"], format='%d/%m/%Y'))
png(filename="Plot1.png")
hist(p[,"Global_active_power"], col="red", main="Global Active Power", xlab="Global Active Power (kilowatts)" )
dev.off()
